//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Appointment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Member_No { get; set; }
        public string Member_Identity { get; set; }
        public string Member_Name { get; set; }
        public string Member_Lastname { get; set; }
        public string Member_Gender { get; set; }
        public string Member_Date_of_birth { get; set; }
        public string Member_Password { get; set; }
    }
}
